// ─── News Sources (verified Sri Lankan media outlets) ───
export const NEWS_SOURCES = [
  {
    id: 'ada-derana',
    name: 'Ada Derana',
    url: 'https://www.adaderana.lk',
    logo: '📺',
    type: 'TV / Digital',
    verified: true,
  },
  {
    id: 'colombo-gazette',
    name: 'Colombo Gazette',
    url: 'https://colombogazette.com',
    logo: '📰',
    type: 'Digital News',
    verified: true,
  },
  {
    id: 'the-island',
    name: 'The Island',
    url: 'https://island.lk',
    logo: '📰',
    type: 'Newspaper / Digital',
    verified: true,
  },
  {
    id: 'newswire',
    name: 'NewsWire',
    url: 'https://www.newswire.lk',
    logo: '📰',
    type: 'Digital News',
    verified: true,
  },
] as const;

// ─── News Categories ───
export const NEWS_CATEGORIES = [
  { id: 'all', label: 'All News', labelSi: 'සියලු පුවත්', labelTa: 'அனைத்து செய்திகள்', icon: 'Globe' },
  { id: 'politics', label: 'Politics', labelSi: 'දේශපාලනය', labelTa: 'அரசியல்', icon: 'Landmark' },
  { id: 'economy', label: 'Economy', labelSi: 'ආර්ථිකය', labelTa: 'பொருளாதாரம்', icon: 'TrendingUp' },
  { id: 'technology', label: 'Technology', labelSi: 'තාක්ෂණය', labelTa: 'தொழில்நுட்பம்', icon: 'Cpu' },
  { id: 'sports', label: 'Sports', labelSi: 'ක්‍රීඩා', labelTa: 'விளையாட்டு', icon: 'Trophy' },
  { id: 'international', label: 'International', labelSi: 'ජාත්‍යන්තර', labelTa: 'சர்வதேசம்', icon: 'Globe2' },
  { id: 'local', label: 'Local', labelSi: 'ප්‍රාදේශීය', labelTa: 'உள்ளூர்', icon: 'MapPin' },
] as const;

// ─── Government Services (verified against official Sri Lankan gov sources) ───
// Sources: immigration.gov.lk, dmc.gov.lk, motortraffic.gov.lk, rgd.gov.lk
export const GOV_SERVICES = [
  {
    id: 'passport',
    title: 'Passport Application',
    titleSi: 'ගමන් බලපත්‍ර අයදුම්පත',
    titleTa: 'கடவுச்சீட்டு விண்ணப்பம்',
    icon: 'BookOpen',
    color: 'from-blue-500 to-cyan-400',
    description: 'Apply for a new passport or renew your existing one.',
    descSi: 'නව ගමන් බලපත්‍රයක් සඳහා අයදුම් කරන්න හෝ පවතින එක අලුත් කරන්න.',
    descTa: 'புதிய கடவுச்சீட்டுக்கு விண்ணப்பிக்கவும் அல்லது ஏற்கனவே உள்ளதை புதுப்பிக்கவும்.',
    processingTime: '3-4 weeks (normal) / 1 day (urgent)',
    fee: 'LKR 3,500 (normal) / LKR 10,000 (urgent)',
    officialSource: 'Department of Immigration & Emigration',
    officialUrl: 'https://www.immigration.gov.lk',
    documents: [
      'National Identity Card (NIC) — original + photocopy',
      'Birth Certificate — original + photocopy',
      'Passport-size colour photographs (3.5cm × 4.5cm, blue background)',
      'Completed application form (Form K35A for new / K35B for renewal)',
      'Old passport (for renewal applications)',
    ],
    steps: [
      'Obtain form K35A (new) or K35B (renewal) from any Divisional Secretariat or download from immigration.gov.lk',
      'Fill all sections in BLOCK CAPITALS with blue or black ink',
      'Get the declaration certified by a Justice of Peace, Attorney-at-Law, or Notary Public',
      'Attach NIC copy, birth certificate copy, and two colour photographs',
      'Submit at Head Office (Battaramulla) or any Regional Passport Office',
      'Pay the applicable fee at the counter',
      'Collect passport after processing (track via immigration.gov.lk)',
    ],
  },
  {
    id: 'nic',
    title: 'NIC Registration',
    titleSi: 'ජාතික හැඳුනුම්පත ලියාපදිංචිය',
    titleTa: 'தேசிய அடையாள அட்டை பதிவு',
    icon: 'CreditCard',
    color: 'from-violet-500 to-purple-400',
    description: 'Register for your National Identity Card (applicable at age 16).',
    descSi: 'ඔබේ ජාතික හැඳුනුම්පත සඳහා ලියාපදිංචි වන්න (වයස අවුරුදු 16 දී අදාළ වේ).',
    descTa: 'உங்கள் தேசிய அடையாள அட்டைக்கு பதிவு செய்யுங்கள் (16 வயதில் பொருந்தும்).',
    processingTime: '2-4 weeks',
    fee: 'LKR 100 (first issue) / LKR 1,000 (duplicate)',
    officialSource: 'Department for Registration of Persons',
    officialUrl: 'https://www.drp.gov.lk',
    documents: [
      'Birth Certificate — original',
      'Grama Niladhari (GN) certification letter',
      'Three passport-size photographs',
      'Parent\'s NIC copies (for first-time applicants)',
      'Marriage certificate (if name changed)',
    ],
    steps: [
      'Obtain application form from Grama Niladhari or Divisional Secretariat',
      'Fill the form completely (get GN certification)',
      'Attach birth certificate, photographs, and parent\'s NIC copies',
      'Submit at Divisional Secretariat office in your area',
      'Receive acknowledgement receipt with reference number',
      'Collect NIC after processing (check status via drp.gov.lk)',
    ],
  },
  {
    id: 'driving-license',
    title: 'Driving License',
    titleSi: 'රියදුරු බලපත්‍රය',
    titleTa: 'ஓட்டுநர் உரிமம்',
    icon: 'Car',
    color: 'from-emerald-500 to-green-400',
    description: 'Apply for a new driving license or renew an existing one.',
    descSi: 'නව රියදුරු බලපත්‍රයක් සඳහා අයදුම් කරන්න හෝ පවතින එක අලුත් කරන්න.',
    descTa: 'புதிய ஓட்டுநர் உரிமத்திற்கு விண்ணப்பிக்கவும் அல்லது ஏற்கனவே உள்ளதை புதுப்பிக்கவும்.',
    processingTime: '1-2 weeks',
    fee: 'LKR 800 (learner\'s) / LKR 1,500 (full license)',
    officialSource: 'Department of Motor Traffic',
    officialUrl: 'https://www.motortraffic.gov.lk',
    documents: [
      'National Identity Card — original + photocopy',
      'Medical certificate from a government-approved doctor',
      'Two passport-size photographs',
      'Learner\'s permit (valid for at least 3 months)',
      'Revenue stamp (LKR 25)',
    ],
    steps: [
      'Apply for a Learner\'s Permit at DMT office with NIC and medical certificate',
      'Pass the written/oral examination at DMT',
      'Practice driving for minimum 3 months with a qualified instructor',
      'Apply for the practical driving test',
      'Pass the practical driving test at DMT',
      'Collect your driving license after processing',
    ],
  },
  {
    id: 'birth-certificate',
    title: 'Birth Certificate',
    titleSi: 'උප්පැන්න සහතිකය',
    titleTa: 'பிறப்புச் சான்றிதழ்',
    icon: 'FileText',
    color: 'from-amber-500 to-yellow-400',
    description: 'Register a birth or obtain a copy of a birth certificate.',
    descSi: 'උපත ලියාපදිංචි කරන්න හෝ උප්පැන්න සහතිකයේ පිටපතක් ලබා ගන්න.',
    descTa: 'பிறப்பைப் பதிவு செய்யுங்கள் அல்லது பிறப்புச் சான்றிதழின் நகலைப் பெறுங்கள்.',
    processingTime: '1-2 weeks (normal registration)',
    fee: 'LKR 50 (within 42 days) / LKR 100 (late registration)',
    officialSource: 'Registrar General\'s Department',
    officialUrl: 'https://www.rgd.gov.lk',
    documents: [
      'Hospital birth notification (Form H-546)',
      'Parent\'s National Identity Cards — original + copies',
      'Parent\'s marriage certificate (if available)',
      'Grama Niladhari certification (for home births)',
    ],
    steps: [
      'Ensure birth is registered within 42 days at the Divisional Secretariat (free)',
      'Obtain hospital birth notification form (H-546)',
      'Father or mother visits the Registrar office in the area of birth',
      'Submit notification form with parent\'s NIC copies',
      'Receive birth registration number and certificate',
      'For late registration (after 42 days), additional GN certification required',
    ],
  },
  {
    id: 'business-registration',
    title: 'Business Registration',
    titleSi: 'ව්‍යාපාර ලියාපදිංචිය',
    titleTa: 'வணிகப் பதிவு',
    icon: 'Building2',
    color: 'from-rose-500 to-pink-400',
    description: 'Register a sole proprietorship or partnership business.',
    descSi: 'තනි හිමිකාරිත්ව හෝ හවුල් ව්‍යාපාරයක් ලියාපදිංචි කරන්න.',
    descTa: 'ஒரு தனி உரிமம் அல்லது கூட்டாண்மை வணிகத்தைப் பதிவு செய்யுங்கள்.',
    processingTime: '1-3 weeks',
    fee: 'LKR 200 - 5,000 (varies by Divisional Secretariat)',
    officialSource: 'Provincial Council / Divisional Secretariat',
    officialUrl: 'https://www.gov.lk',
    documents: [
      'NIC of business owner(s) — original + copies',
      'Address verification (utility bill or Grama Niladhari letter)',
      'Revenue stamp (LKR 25)',
      'Completed BRA form',
      'Partnership deed (for partnerships)',
    ],
    steps: [
      'Decide business structure: sole proprietorship or partnership',
      'Obtain BRA (Business Registration Act) form from Divisional Secretariat',
      'Fill the form with proposed business name and details',
      'Submit with NIC copies, address proof, and revenue stamp',
      'Pay the registration fee',
      'Collect Business Registration Certificate',
      'Register for tax at Inland Revenue Department if annual turnover exceeds LKR 500,000',
    ],
  },
  {
    id: 'vehicle-registration',
    title: 'Vehicle Registration',
    titleSi: 'වාහන ලියාපදිංචිය',
    titleTa: 'வாகனப் பதிவு',
    icon: 'Truck',
    color: 'from-sky-500 to-blue-400',
    description: 'Register a new vehicle or transfer vehicle ownership.',
    descSi: 'නව වාහනයක් ලියාපදිංචි කරන්න හෝ වාහන හිමිකාරිත්වය මාරු කරන්න.',
    descTa: 'புதிய வாகனத்தை பதிவு செய்யுங்கள் அல்லது வாகன உரிமையை மாற்றுங்கள்.',
    processingTime: '1-2 weeks',
    fee: 'LKR 2,500 - 15,000 (varies by vehicle type)',
    officialSource: 'Department of Motor Traffic',
    officialUrl: 'https://www.motortraffic.gov.lk',
    documents: [
      'Customs declaration (CUSDEC) for imported/new vehicles',
      'Valid vehicle insurance certificate',
      'Emission test certificate',
      'NIC of owner — original + copy',
      'CR (Certificate of Registration) form',
    ],
    steps: [
      'Obtain CR form from Department of Motor Traffic (DMT)',
      'Get vehicle inspected at DMT or authorised centre',
      'Obtain valid insurance and emission test certificate',
      'Submit CR form with all supporting documents',
      'Pay registration fee based on vehicle category',
      'Collect Registration Certificate (CR book) and number plates',
    ],
  },
] as const;

// ─── Languages ───
export const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: '🇬🇧' },
  { code: 'si', name: 'Sinhala', nativeName: 'සිංහල', flag: '🇱🇰' },
  { code: 'ta', name: 'Tamil', nativeName: 'தமிழ்', flag: '🇱🇰' },
] as const;

// ─── Demo News Data (realistic, based on common Sri Lankan news topics) ───
export const DEMO_NEWS = [
  {
    id: '1',
    title: 'Central Bank Maintains Policy Interest Rates Unchanged',
    summary: 'The Central Bank of Sri Lanka decided to maintain the Standing Deposit Facility Rate (SDFR) and Standing Lending Facility Rate (SLFR), citing stable inflation and economic recovery.',
    source: 'Daily News',
    sourceUrl: 'https://www.dailynews.lk',
    sourceVerified: true,
    category: 'economy',
    imageUrl: 'https://images.unsplash.com/photo-1526304640581-d334cdbbf45e?w=600&h=400&fit=crop',
    publishedAt: '2 hours ago',
    district: 'Colombo',
  },
  {
    id: '2',
    title: 'Sri Lanka IT/BPO Exports Reach $1.7 Billion Milestone',
    summary: 'Sri Lanka\'s Information Technology and Business Process Outsourcing sector has achieved $1.7 billion in export revenue, making it the 5th largest forex earner.',
    source: 'Ada Derana',
    sourceUrl: 'https://www.adaderana.lk',
    sourceVerified: true,
    category: 'technology',
    imageUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop',
    publishedAt: '4 hours ago',
    district: 'Colombo',
  },
  {
    id: '3',
    title: 'Sri Lanka Cricket Announce Squad for Upcoming Test Series',
    summary: 'Sri Lanka Cricket (SLC) has announced an 18-member squad for the upcoming home Test series, with a mix of experienced players and emerging talent from domestic cricket.',
    source: 'NewsFirst',
    sourceUrl: 'https://www.newsfirst.lk',
    sourceVerified: true,
    category: 'sports',
    imageUrl: 'https://images.unsplash.com/photo-1531415074968-036ba1b575da?w=600&h=400&fit=crop',
    publishedAt: '5 hours ago',
    district: 'Colombo',
  },
  {
    id: '4',
    title: 'Parliament Approves Amendment to Education Ordinance',
    summary: 'The Sri Lankan Parliament has approved amendments to the Education Ordinance introducing digital literacy into the national curriculum for grades 6-13.',
    source: 'Daily Mirror',
    sourceUrl: 'https://www.dailymirror.lk',
    sourceVerified: true,
    category: 'politics',
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c476?w=600&h=400&fit=crop',
    publishedAt: '6 hours ago',
    district: 'Sri Jayewardenepura Kotte',
  },
  {
    id: '5',
    title: 'Colombo Port Records Highest Container Throughput',
    summary: 'The Port of Colombo has recorded its highest monthly container throughput, reinforcing its position as a key transhipment hub in the Indian Ocean region.',
    source: 'Sunday Times',
    sourceUrl: 'https://www.sundaytimes.lk',
    sourceVerified: true,
    category: 'economy',
    imageUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=600&h=400&fit=crop',
    publishedAt: '8 hours ago',
    district: 'Colombo',
  },
  {
    id: '6',
    title: 'CEB Announces Solar Power Expansion in Southern Province',
    summary: 'The Ceylon Electricity Board (CEB) has announced plans to expand solar power capacity in Hambantota and Matara districts as part of the national renewable energy target.',
    source: 'Daily News',
    sourceUrl: 'https://www.dailynews.lk',
    sourceVerified: true,
    category: 'local',
    imageUrl: 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600&h=400&fit=crop',
    publishedAt: '1 day ago',
    district: 'Hambantota',
  },
] as const;

// ─── Chat Suggestions ───
export const CHAT_SUGGESTIONS = [
  { text: 'Latest news in Sri Lanka', icon: 'Newspaper' },
  { text: 'How to apply for a passport?', icon: 'BookOpen' },
  { text: 'NIC application process', icon: 'CreditCard' },
  { text: 'Weather today in Colombo', icon: 'CloudSun' },
  { text: 'Government services near me', icon: 'Landmark' },
  { text: 'Business registration guide', icon: 'Building2' },
] as const;

// Sinhala chat suggestions
export const CHAT_SUGGESTIONS_SI = [
  { text: 'ශ්‍රී ලංකාවේ නවතම පුවත්', icon: 'Newspaper' },
  { text: 'ගමන් බලපත්‍රයක් සඳහා අයදුම් කරන්නේ කෙසේද?', icon: 'BookOpen' },
  { text: 'ජාතික හැඳුනුම්පත අයදුම් ක්‍රියාවලිය', icon: 'CreditCard' },
  { text: 'අද කොළඹ කාලගුණය', icon: 'CloudSun' },
  { text: 'මට ආසන්නම රජයේ සේවා', icon: 'Landmark' },
  { text: 'ව්‍යාපාර ලියාපදිංචි මාර්ගෝපදේශය', icon: 'Building2' },
] as const;

// Tamil chat suggestions
export const CHAT_SUGGESTIONS_TA = [
  { text: 'இலங்கையின் சமீபத்திய செய்திகள்', icon: 'Newspaper' },
  { text: 'கடவுச்சீட்டுக்கு விண்ணப்பிப்பது எப்படி?', icon: 'BookOpen' },
  { text: 'NIC விண்ணப்ப செயல்முறை', icon: 'CreditCard' },
  { text: 'இன்று கொழும்பு வானிலை', icon: 'CloudSun' },
  { text: 'அரசாங்க சேவைகள் என் அருகில்', icon: 'Landmark' },
  { text: 'வணிகப் பதிவு வழிகாட்டி', icon: 'Building2' },
] as const;
